---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desktop-os
# description will be included in the image's metadata
description: OS image for desktop.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 41 # latest is also supported if you want new updates ASAP

stages:
  - name: regreet
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git # Install git
          - git clone https://github.com/rharish101/ReGreet.git
          - cd ReGreet && cargo build --release
          # - mkdir -p /out/ && mv $CARGO_HOME/bin/hx /out/hx && mv runtime /out/ # Move bin and runtime

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - tailscale
      - zsh
      - kitty
      - greetd
      - gtkgreet
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - com.visualstudio.code
        - com.logseq.Logseq
        - org.zotero.Zotero
        - org.flameshot.Flameshot
        - com.bitwarden.desktop
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages
  - type: files
    files:
      - source: system/etc/greetd
        destination: /etc/greetd # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: systemd
    system:
      disabled:
        - sddm
      enabled:
        - greetd

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

