[terminal]
# The VT to run the greeter on.
vt = 1

# The default session, also known as the greeter.
[default_session]
# greeter command (i.e. agreety, or some of the others as needed)
command = "sway --config /etc/greetd/sway-gtkgreet"
user = "greetd"
